"""collection settings

Revision ID: fdf9f20902f2
Revises: ce00f21b05ff
Create Date: 2022-05-30 01:17:03.071566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf9f20902f2'
down_revision = 'ce00f21b05ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('catalog_number_regex', sa.String(length=150), nullable=True))
    op.add_column('collection', sa.Column('web_base', sa.String(length=150), nullable=True))
    op.add_column('collection', sa.Column('url_base', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'url_base')
    op.drop_column('collection', 'web_base')
    op.drop_column('collection', 'catalog_number_regex')
    # ### end Alembic commands ###
